# @package _group_
#default_root_dir: None
gradient_clip_val: 0
gpus: 0
auto_select_gpus: False
log_gpu_memory: None
overfit_batches: 0.0
track_grad_norm: -1
accumulate_grad_batches: 1
max_epochs: 1000
min_epochs: 1
#max_steps: None
#min_steps: None
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
val_check_interval: 1.0
precision: 32
#resume_from_checkpoint: None
deterministic: False
reload_dataloaders_every_epoch: False
auto_lr_find: False
auto_scale_batch_size: False
